# Streamlit Cloud Secrets Configuration
# Add these secrets in Streamlit Cloud dashboard instead of committing this file

# OpenAI API Key
# OPENAI_API_KEY = "your-openai-api-key-here"

# Note: This file should NOT be committed to Git
# It's here as a template. Configure actual secrets in Streamlit Cloud.

